//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietHDBan
    {
        public int IdCTHD { get; set; }
        public string MaHang { get; set; }
        public string MaHDBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual tblHang tblHang { get; set; }
        public virtual tblHDBan tblHDBan { get; set; }
    }
}
