//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHang
    {
        public tblHang()
        {
            this.tblChiTietHDBans = new HashSet<tblChiTietHDBan>();
        }
    
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public Nullable<int> IdChatLieu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> DonGiaNhap { get; set; }
        public string Anh { get; set; }
        public string GiaBan { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tblChatLieu tblChatLieu { get; set; }
        public virtual ICollection<tblChiTietHDBan> tblChiTietHDBans { get; set; }
    }
}
