//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHDBan
    {
        public tblHDBan()
        {
            this.tblChiTietHDBans = new HashSet<tblChiTietHDBan>();
        }
    
        public string MaHDBan { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public string MaKhach { get; set; }
        public string MaNhanVien { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        public virtual ICollection<tblChiTietHDBan> tblChiTietHDBans { get; set; }
        public virtual tblKhachHang tblKhachHang { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
